### ISSUE TITLE
Migrate to Circle CI

### ISSUE THREAD

**Issue by Bhargavasomu** [ethereum/pyrlp#104]
We should probably migrate to `Circle CI`, as `Travis CI` is kind of slow and also for the reason that 
`circle ci` is widely used among the other repositories.

**Comment by pipermerriam** [comment]
setting up the necessary things in our CircleCI config so that once a config file is loaded into this repo it will start working.

**Comment by Bhargavasomu** [comment]
This can now be closed by #107
