### ISSUE TITLE
Live docs link to very old version of docs

### ISSUE THREAD

**Issue by laalaguer** [ethereum/pyrlp#123]
Hi, 

I found on the readthedocs site:
https://pyrlp.readthedocs.io/en/latest/tutorial.html

```
>>> from rlp.text import text
>>> encode(u'Ðapp')
'\x85\xc3\x90app'
>>> decode('\x85\xc3\x90app', text)
u'\xd0app'
>>> print decode('\x85\xc3\x90app', text)
Ðapp

```

Which is wrong by `from rlp.text import text`,

but instead in the source code:
https://github.com/ethereum/pyrlp/blob/master/docs/tutorial.rst

`from rlp.sedes import binary`

Maybe the document version is not updated yet with the source code on github?

**Comment by cburgdorf** [comment]
Thanks for reporting. In fact, it looks like the live docs link to a [very old version](https://github.com/jnnk/pyrlp/blob/master/docs/tutorial.rst) of the docs.

**Comment by carver** [comment]
@jnnk can you add me as a maintainer on readthedocs, so I can get the docs updating again?
https://readthedocs.org/projects/pyrlp/

My RTD account is `@carver`.

**Comment by carver** [comment]
The docs still need a lot of updating, but now at least they are building from the right source. Thanks for reporting, and for your patience waiting for this to get resolved!
