### ISSUE TITLE
How to disable the warning "Consider installing rusty-rlp to improve pyrlp"?

### ISSUE THREAD

**Issue by max-block** [ethereum/pyrlp#128]
Please, tell me how to disable printing "Consider installing rusty-rlp to improve pyrlp" warning.
I was trying `logging.getLogger("rlp").setLevel(logging.ERROR)`, but it doesn't help.

**Comment by oberstet** [comment]
this is indeed annoying, and disabling warnings for the whole app isn't a viable option.

solution is to remove: https://github.com/ethereum/pyrlp/blob/35eb04c6d35555385d8f69478f67665937c77327/rlp/codec.py#L26

**Comment by oberstet** [comment]
https://github.com/ethereum/pyrlp/pull/129

**Comment by dataforestLTD** [comment]
logger.warning(
        "You're good enough, you're smart enough, and gosh darnit, people like you"
    )

I decided that I'd rather get a nice message every time I spin up my development server.

**Comment by jluuM2** [comment]
this works:
`# remove annoying rust add`
`logging.disable(level=logging.WARNING)`
`import web3`
`logging.disable(level=logging.NOTSET)`
