### ISSUE TITLE
Inconsistent encoding of 0 in int_to_big_endian

### ISSUE THREAD

**Issue by jhoenicke** [ethereum/pyrlp#29]
Python 3 and python 2.7 implementations encode 0 in diffent ways:

```
Python 3.5.2 (default, Jul  5 2016, 12:43:10) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import rlp
>>> rlp.utils.int_to_big_endian(0)
b''
>>> 
>python2
Python 2.7.12 (default, Jul  1 2016, 15:12:24) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import rlp
>>> rlp.utils.int_to_big_endian(0)
'\x00'
```

I think, the python3 encoding is the right one.  0 should be encoded by a zero length bytestring.

**Comment by janx** [comment]
I think py2 is the correct implementation, since `int_to_big_endian` converts `int` to big endian bytes, not RLP encoded bytes.

cc @heikoheiko @konradkonrad

**Comment by jhoenicke** [comment]
I think it is confusing and lead to errors if `rlp.encode(0)` is not the same as `rlp.encode(int_to_big_endian(0))`, while this holds for any other number except `0`. 

It is so confusing that someone was already claiming that the rlp encoding of '\x00' should be '\x80' instead of '\x00'.

There is no documentation for rlp.utils to judge from.  Is it even meant to be a public function?  It is useful to have a function to convert numbers to byte sequences that is rlp encoding preserving.

**Comment by pipermerriam** [comment]
This issue has been since reconciled.  Both functions are now behaving the same.
