### ISSUE TITLE
Remove support for non-bytes inputs

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/pyrlp#30]
Proposal to remove support for non-bytes input values for the RLP API.

### Motivation

The RLP API is a *low* level tool for encoding/decoding.  Being a low level tool it seems acceptable for the tool to only support inputs of a specific format.

By supporting both text and bytes inputs the RPL library adds overhead for the checking and conversion step.  Python ethereum clients will benefit from the removal of this overhead, especially in situations where lots of reads and writes are happening in the trie database.

### Other examples of this

The `json` library from the stdlib only accepts text (unicode) inputs.

### Proposed way to implement this.

1. On all public APIs,  `rlp.encode, rlp.decode, Serializable.deserialize, rlp.lazy_decode` begin issuing `DeprecationWarning` warnings.
2. After some period of time, replace these deprecation warnings and calls to `str_to_bytes` with something akin to the following.

```python
if not isinstance(value, bytes):
    raise TypeError("Must be a bytes-type value")   # error message would be more specific for each case.
```

I suggest giving a 👍 / 👎  to the main issue to gauge support.

**Comment by step21** [comment]
Is this why the docs say there is rlp.text or rlp.sedes.text whereas I cannot find this in the code?
