### ISSUE TITLE
decode_hex fails for Python3

### ISSUE THREAD

**Issue by reverendus** [ethereum/pyrlp#39]
From `utils_py3.py`:

```
def decode_hex(s):
    if isinstance(s, str):
        return bytes.fromhex(s)
    if isinstance(b, (bytes, bytearray)):
        return binascii.unhexlify(s)
    raise TypeError('Value must be an instance of str or bytes')
```

variable `b` doesn't seem to be defined which in fact makes that method not work in Python 3.6.1.

**Comment by pipermerriam** [comment]
Fixed, working on getting `0.5.1` released with this change.  Thanks for finding and fixing.
