### ISSUE TITLE
Change to use `master` as primary branch.

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/pyrlp#48]
### What is wrong

py-rlp uses `develop` as it's primary development branch.  This is inline with all of the *old* ethereum python codebases, but incongruent with all of the *newer* python codebases.

### How can it be fixed

I propose we change the primary branch to be `master`.

**Comment by pipermerriam** [comment]
Looking for feedback from those who've been maintaining this codebase.  I'm looking to conceptually migrate it to be under the suite of tools that I'm shepherding and in doing so I'd like to make this change for conformity sake.

**Comment by jannikluhn** [comment]
No objections
