### ISSUE TITLE
API refactor for rlp.Serializable

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/pyrlp#61]
I've some thoughts on how we might change `rlp.Serializable`.

### Current features

- immutable vs. mutable objects (`make_mutable`, `make_immutable`).
- attribute access to fields
- instantiation with either `*args` or `**kwargs`
- `cls.exclude` API for creating classes with a subset of fields

### Inefficiencies

- mutability checks at runtime
- field assignment done exclusively through `__setattr__` (60% faster to use direct attribute assignment)
- `obj.fields` is non-ideal since it disallows the use of any field named `fields`

### Solution

- use `collections.namedtuple` for immutable versions of the object.  Fields are naturally ordered, and immutability is enforced by default.
- use a dynamically constructed class for mutable versions of the object.

**Comment by pipermerriam** [comment]
@carver and @gsalgado thoughts?

**Comment by carver** [comment]
Seems reasonable. It would be nice to think through how we would need to re-work current subclasses, like: https://github.com/ethereum/eth-rlp/blob/master/eth_rlp/main.py#L13

**Comment by pipermerriam** [comment]
> It would be nice to think through how we would need to re-work current subclasses

The *one* major breaking change that I want to make is removal of `obj.fields`.  Otherwise, I don't see anything in the linked example that would need to be reworked.  I'm implementing `__iter__` for use internally, so you'd even be able to remove that from the subclass.

**Comment by wjmelements** [comment]
I don't see any `make_mutable`. The only apparent way to make it mutable is to set `_in_mutable_context` to `True`

**Comment by carver** [comment]
IIRC we settled on an immutable-only approach.
