### ISSUE TITLE
Version 1.0 breaks functionality in pyethereum

### ISSUE THREAD

**Issue by dragos-vlad** [ethereum/pyrlp#87]
Hello, 

The new version breaks an import in pyethereum. Bellow I have attached the traceback.

```
     from ethereum.utils import check_checksum
   File "/usr/local/lib/python3.6/site-packages/ethereum/__init__.py", line 11, in <module>
     from . import slogging  # noqa
   File "/usr/local/lib/python3.6/site-packages/ethereum/slogging.py", line 6, in <module>
     from ethereum.utils import bcolors, is_numeric
   File "/usr/local/lib/python3.6/site-packages/ethereum/utils.py", line 13, in <module>
     from rlp.utils import decode_hex, encode_hex, ascii_chr, str_to_bytes
 ImportError: cannot import name 'decode_hex'
```

**Comment by pipermerriam** [comment]
You can just pin the version in pyethereum to `rlp<1.0`.  We released with a major version bump because there are breaking changes.

**Comment by dragos-vlad** [comment]
I already did that, however this needs to be pined in the pyetherium requirements since this realease breaks the pyetherium library.

**Comment by der-Daniel** [comment]
Where do I pin the version?
I was just using pip for installing pyethereum.

**Comment by pipermerriam** [comment]
haven't tested it but you can try `pip install ethereum "rlp<1"`

**Comment by dragos-vlad** [comment]
It works. The way I fixed my problem was to pin in `requirements.txt` the `rlp` library to `<1`.
