### ISSUE TITLE
No caching of RLP when decoding a List of Serializable items

### ISSUE THREAD

**Issue by gsalgado** [ethereum/pyrlp#93]
When we decode a list of Serializable items, the individual items should get their `_cached_rlp` set, just like when we decode an individual Serializable

**Comment by gsalgado** [comment]
Apart from #94, another possible solution I can think of would be to change `consume_payload()` to return the RLP split per-item, and then use that in `decode()` to set the `_cached_rlp` of each item when `is_sequence(obj)` is true. But I've already spent a few hours on that and can't seem to figure it out. It'd be great if someone could help me out with this... maybe I'm missing something

**Comment by pipermerriam** [comment]
`obj._cached_rlp` gets set here in `rlp.decode`

- https://github.com/ethereum/pyrlp/blob/master/rlp/codec.py#L224-L225

It looks like `List` and `CountableList` bypass that by calling `sedes.deserialize` directly.

- https://github.com/ethereum/pyrlp/blob/master/rlp/sedes/lists.py#L88
- https://github.com/ethereum/pyrlp/blob/master/rlp/sedes/lists.py#L138

How about we change those to instead use `rlp.decode` for the inner decoding as well?

**Comment by gsalgado** [comment]
AIUI, `decode()` takes an RLP-encoded bytes whereas `Serializable.deserialize()` take a sequence of items already decoded.

**Comment by gsalgado** [comment]
`Serializable.deserialize()` is in fact called by `decode()`

**Comment by pipermerriam** [comment]
`Serializable.deserialize()` is in fact called by `decode()`

Right, I didn't do extensive investigation, but my thought was we could use `rlp.decode` to prevent duplicating the`_cached_rlp` setter logic.

**Comment by pipermerriam** [comment]
And now after some experimentation I see that isn't really viable.  The only route I see that *could* make this work a bit cleaner would be if we modified the workflow of `consume_item` to return no just the `serial` but the full `rlp` of the item so that we could use that within `rlp.decode` to set the cache properly.

**Comment by gsalgado** [comment]
Hmm, right, that sounds like what I said in https://github.com/ethereum/pyrlp/issues/93#issuecomment-409895988? That is what I couldn't figure out *how* to do

**Comment by pipermerriam** [comment]
Alternate would be to try and figure out a better way to have unified caching on these items.  This could either be in replacement of item level caching via the `_cached_rlp` property like exists now, or an additional layer.

Here's an idea on how we might be able to get a unified caching strategy in place.

- We remove the singleton nature of the `encode/decode/encode_raw` functions in favor of them living on an object.  We can still expose them as *if* they were functions like follows

```python
# rlp/codec.py
class RLP:
    def encode(...):
        ...
    def encode_raw(...):
        ...
    def decode(...):
        ...

_default_rlp = RLP()

encode = _default_rlp.encode
decode = _default_rlp.decode
encode_raw = default_rlp.encode_raw
```

With this, we can establish a way to put a single cache on the `RLP` class.  In py-evm (and maybe py-trie also) we can then use a local instance of the `RLP` object with our own cache.

Note that this still doesn't fix the issue at hand, so we'd still need something to solve this issue which may be orthoganal.

**Comment by gsalgado** [comment]
https://gist.github.com/gsalgado/c55a61ff5660fc03075268fa8089a6c5 was my first attempt. with it my test passes, but it breaks others as the `serial` argument to `Serializable.deserialize()` is now a list of two-tuples, first being the item and second being its rlp representation. I also didn't like the fact that it moved the responsibility of caching to `Serializable.deserialize()`, so I tried to find an alternative solution, but that's when I got stuck

**Comment by pipermerriam** [comment]
Take a look at https://github.com/gsalgado/pyrlp/pull/1

It attempts to change how we consume RLP strings to not perform a full depth first de-serialization, but going that route would require a decent internal refactor.

**Comment by gsalgado** [comment]
@pipermerriam I couldn't really understand how that would be used, and nor what the needed refactoring would look like, so I decided to give another chance to [that first idea I'd tried](https://gist.github.com/gsalgado/c55a61ff5660fc03075268fa8089a6c5), and now I was able to get something that is not too invasive and works: https://github.com/ethereum/pyrlp/pull/95
