### ISSUE TITLE
ImportError: cannot import name 'encode_hex'

### ISSUE THREAD

**Issue by ztlovemst11** [ethereum/pyrlp#96]
from rlp.utils import encode_hex
ImportError: cannot import name 'encode_hex'

why？
is that don't exist？

**Comment by pipermerriam** [comment]
That function was removed from this library.  Anything under a `utils` namespace is considered a private api and subject to breaking changes like this without a deprecation cycle.

You can get an `encode_hex` function from the `eth-utils` library if you'd like.  

https://github.com/ethereum/eth-utils

**Comment by carver** [comment]
\<meta>
@pipermerriam FWIW, when I was new to the eth-* projects, it wasn't obvious to me at all that `util` was private. I thought it was utilities provided by the library for external use. I'd be in favor of slowly shifting this standard to a new package name, like `internal`, which is hopefully more transparent about not being for public use.
\</meta>

**Comment by ztlovemst11** [comment]
thanks ，I solved the problem by eth-utils
